### PR TITLE
Add Site Navigation component

### LINKED ISSUE #8: Component: Site Navigation
# Stories

- As a reader of a guide, I want to see what sections are in the guide so that I know if the guide is relevant and has what I'm trying to learn.
- As a reader of a guide, I want to be able to navigate around so that I can get to the information I'm looking for.

# Notes

- This ticket covers both design and development tasks. Change assignee of the ticket based on who has the next action, and remove the person or people that no longer have an action. It's expected that a ticket will get passed back and forth a few times.
- See the [component doc](https://docs.google.com/document/d/1yC4y262CSiQ1iBqxjXPxFsOJJ1y0Z6WcDdnqY7sKnco/edit#heading=h.yuzn4ifuwtwx) for more information

# Done When

- [x] UX: Component design is drafted and shared for review
- [x] Dev: Component design is reviewed and approved
- [ ] Peer UX: Compontent design is reviewed and approved
- [ ] Dev: Component style and markup is developed and shared for PR review
- [ ] Dev: Documentation on how to use component is drafted
- [ ] UX: Component style and markup is reviewed and approved
- [ ] Peer Dev: Component style and markup is reviewed and approved
- [ ] Component is available for use

### PR DESCRIPTION
**Pull request by jrubenoff**
Closes #8.

### Preview this component

- [Site Navigation](https://site-navigation--bloom-guides-template.netlify.app/components/site-navigation/)

### Changes
- Adds the Site Navigation component and "Jump to a section" [`<dialog>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog) as an 11ty include
- Adds the Site Navigation include to the homepage
- Adds `button.css` for site-wide button styles
- Adds a small `<script>` tag at the end of `base.njk` to show and hide the `<dialog>` element. ([See this MDN page on `showModal()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/showModal) for more info.)

### Notes

I've added a `bootstrap-icons` SVG sprite sheet that's identical to similar PRs.

### CODE REVIEW

**Review by SMakaiTakori — APPROVED** [review]
Thanks again for leaving comments behind, I know it will be very helpful in the future. This PR is ready for review from @admoorgit

**Review by admoorgit — CHANGES_REQUESTED** [review]
@SMakaiTakori this looks great! One fix: on mobile we'll need to make some adjustments, as the stack is a little awk. Ideally, title on top, sections on left, search on right.

**Comment by jrubenoff** [comment]
@admoorgit This was an oversight on my part. Happy to fix (for free) by Wednesday EOD.

**Comment by jrubenoff** [comment]
@admoorgit The layout on small screens should now match [the screencasts here.](https://github.com/bloom-works/guides-template/issues/8#issuecomment-1601985414

**Comment by SMakaiTakori** [comment]
@jrubenoff I opened the deploy preview for the navigation component and the `Sections` aren't opening on desktop. The drawer opens on mobile but it is empty and doesn't display any links/chapters for users to navigate to.

**Comment by SMakaiTakori** [comment]
@jrubenoff I opened the deploy preview for the navigation component and the Sections aren't opening on desktop. The drawer opens on mobile but it is empty and doesn't display any links/chapters for users to navigate to. Maybe something changed when you added the mobile view?

**Comment by jrubenoff** [comment]
@SMakaiTakori Good catch! This should be fixed, I think.

**Review by admoorgit — APPROVED** [review]
LGTM

**Pull request merged**
