### PR TITLE
Add base CSS styles

### LINKED ISSUE #12: Styles: Typography
# Stories

- As a reader of a guide, I want to different kinds of text to appear different so that I can understand how the content is organized and follow it more easily.

# Notes

- See [the component doc](https://docs.google.com/document/d/1yC4y262CSiQ1iBqxjXPxFsOJJ1y0Z6WcDdnqY7sKnco/edit#heading=h.o18mksxm99io) for more information
- This ticket covers both design and development tasks. Change assignee of the ticket based on who has the next action, and remove the person or people that no longer have an action. It's expected that a ticket will get passed back and forth a few times.

# Done When

- [ ] UX: Design is drafted and shared for review
- [ ] Dev: Design is reviewed and approved
- [ ] Peer UX: Design is reviewed and approved
- [ ] Dev: Style is developed and shared for PR review
- [ ] UX: Style is reviewed and approved
- [ ] Peer Dev: Style and markup is reviewed and approved
- [ ] Style is available for use

### PR DESCRIPTION
**Pull request by jrubenoff**
Closes #12. I'm opening this PR now, before closing #5 and #6, because all my components depend on these base styles.

### Changes

- Remove any layout partials we won't use
- Replace Bootstrap with normalize.css
- Add CSS variables alongside typography and layout styles
- Add Google Fonts `<link>` tags to `<head>`

Most of these styles are pulled from [jrubenoff/storybook-sass](https://github.com/jrubenoff/storybook-sass). Hopefully it has all the comments you need, but let me know if there's anything here that needs clarification.

@admoorgit If you want to leave feedback on typography, it's probably easiest to do so here!

### CODE REVIEW

**Comment by jrubenoff** [comment]
I should also mention that, in lieu of a build system, I'm using [this tip](https://www.11ty.dev/docs/quicktips/concatenate/) to concatenate all my CSS files.

Might be nice to add minification down the line. @SMakaiTakori Let me know if there's a CSS build system you prefer!

**Comment by jeffmaher** [comment]
@admoorgit to jump in on this tomorrow. @SMakaiTakori to jump in later today.

**Review by SMakaiTakori — APPROVED** [review]
@jrubenoff I really appreciate the detailed comments in the `css` files. This all looks great to me!

**Comment by admoorgit** [comment]
Ch-ch-CHANGES @jrubenoff ...
- H1-H3: remove text-transform: uppercase — we want dat sentence case!
- Let's change all dark gray to black

By style:
H1: font-size: 3rem, weight: 700, color: black; line-height: 1.1;
H2: font-size: 2.25rem, weight: 700, color: black; line-height: 1.2; border-color: #19825A
H3: font-size: 1.875rem, weight: 700, color: #19825A, line-height: 1.2; 
H4: s'ok!
H5: font-weight: 700, color: #19825A; 
H6: color: #19825A; otherwise s'ok!
P: font-size: 1.25rem;
UL/OL: 
- can we indent these a bit? 2.5rem?
- decrease spacing between list items so they're grouped better visually. maybe 25% decrease? 


Let me know if you have any questions!

**Review by admoorgit — CHANGES_REQUESTED** [review]
Ch-ch-CHANGES @jrubenoff ...

H1-H3: remove text-transform: uppercase — we want dat sentence case!
Let's change all dark gray to black
By style:
H1: font-size: 3rem, weight: 700, color: black; line-height: 1.1;
H2: font-size: 2.25rem, weight: 700, color: black; line-height: 1.2; border-color: #19825A
H3: font-size: 1.875rem, weight: 700, color: #19825A, line-height: 1.2;
H4: s'ok!
H5: font-weight: 700, color: #19825A;
H6: color: #19825A; otherwise s'ok!
P: font-size: 1.25rem;
UL/OL:

can we indent these a bit? 2.5rem?
decrease spacing between list items so they're grouped better visually. maybe 25% decrease?

Let me know if you have any questions!
- a.

**Comment by jrubenoff** [comment]
@admoorgit I believe I've addressed everything here: https://typography--bloom-guides-template.netlify.app/

(I also added an example for caption text, to give you an idea of the smallest type size for some components.)

**Comment by jrubenoff** [comment]
@admoorgit I also just pushed up a fix for the H2's bottom border when the element spans multiple lines.

| Before | After |
|--------|-------|
|   CleanShot 2023-06-23 at 08 19 39@2x     |     CleanShot 2023-06-23 at 08 19 31@2x |

**Comment by jeffmaher** [comment]
Updated the branch and applied a release label (and might do one more time after another PR is reviewed). Otherwise, ready for @admoorgit 's review.

**Review by admoorgit — APPROVED** [review]
@SMakaiTakori  Had a late-breaking change to swap body copy from Condensed to regular Barlow for readability sake. S'ok for you?

TO BE DETERMINED: Removal of italic fonts (we may use bold instead), but need approval.

**Comment by SMakaiTakori** [comment]
> @SMakaiTakori Had a late-breaking change to swap body copy from Condensed to regular Barlow for readability sake. S'ok for you?
> 
> TO BE DETERMINED: Removal of italic fonts (we may use bold instead), but need approval.

@admoorgit that works for me! We can always adjust the italic fonts later on.

**Pull request merged**
