### PR TITLE
Add Site Footer component

### LINKED ISSUE #11: Component: Site Footer
# Stories

- As a reader of a guide, I want to know who created the guide so that I can learn more about who created the guide.
- As a reader of a guide, I want to be able to navigate to information about the guide's authoring org, so I can understand what experiences informed the guide's creation.

# Notes

- See [the component doc](https://docs.google.com/document/d/1yC4y262CSiQ1iBqxjXPxFsOJJ1y0Z6WcDdnqY7sKnco/edit#heading=h.edrxno737s72) for more information
- This ticket covers both design and development tasks. Change assignee of the ticket based on who has the next action, and remove the person or people that no longer have an action. It's expected that a ticket will get passed back and forth a few times.

# Done When

- [ ] UX: Component design is drafted and shared for review
- [ ] Dev: Component design is reviewed and approved
- [ ] Peer UX: Compontent design is reviewed and approved
- [ ] Dev: Component style and markup is developed and shared for PR review
- [ ] Dev: Documentation on how to use component is drafted
- [ ] UX: Component style and markup is reviewed and approved
- [ ] Peer Dev: Component style and markup is reviewed and approved
- [ ] Component is available for use

### PR DESCRIPTION
**Pull request by jrubenoff**
Closes #11.

You should be able to preview the footer [on this page.](https://site-footer--bloom-guides-template.netlify.app/components/site-footer/)

### Changes
- Adds the Site Footer component as an 11ty include
- Add the `envelope` and `linkedin` icons to a new `_includes/icons` folder
- Adds a new, higher-res version of the SBA WOSB logo that's probably worth copying over to the main Bloom site

### Notes

To keep merge conflicts to a minimum, I'm using the file structure that I noticed [web.dev's 11ty instance](https://github.com/GoogleChrome/web.dev/blob/main/.eleventy.js#L195-L220) using:

- Each shortcode's markup is in its own dedicated file in `_includes`.
- The `common-tags` package strips out whitespace, ensuring the component renders correctly.

I've also added a `bootstrap-icons` SVG sprite sheet identical to what's in #31.

### CODE REVIEW

**Comment by jrubenoff** [comment]
Adam's feedback from a Zoom call:

- Move the SBA logo and text to the bottom, next to the Bloom Works copyright info
- Bloom should discuss what the footer navigation should have before this is merged, but for now Josh will leave it as-is

**Comment by jrubenoff** [comment]
@admoorgit It was a bit challenging to fit the SBA text in the bottom row and keep it looking good, but [here's my attempt](https://site-footer--bloom-guides-template.netlify.app/components/site-footer/) if you want to take a look!

**Review by SMakaiTakori — APPROVED** [review]
This looks good to me @jrubenoff , ready for review from @admoorgit when ready.

**Review by admoorgit — APPROVED** [review]
This works just fine until we revisit footer content in the future.

**Pull request merged**
