### PR TITLE
Small typography fixes

### PR DESCRIPTION
**Pull request by jrubenoff**
### Changes

- Headings should use Barlow Semi Condensed, not Barlow, as per Adam's feedback in #20 (oops)
- Link underlines are now the same color as the link
- Link underlines on heading styles are a bit thicker for better visibility

### CODE REVIEW

**Review by SMakaiTakori — COMMENTED** [review]
@jrubenoff I saw your comment about updating the font type but I don't see that change in the code so just alerting you to that.

**Comment by jrubenoff** [comment]
@SMakaiTakori It's this line right here: https://github.com/bloom-works/guides-template/pull/37/files#diff-8bc2b10da94d8e4d69c27f19ace3acd19dcab738f002abb51388598c971d5733R62

**Review by admoorgit — APPROVED** [review]
This works for me!

**Review by SMakaiTakori — APPROVED** [review]
Looks good!

**Pull request merged**
