### PR TITLE
Remove Resources section from the footer

### PR DESCRIPTION
**Pull request by jeffmaher**
## Pull Request Background

Removes the `Resources` area from the footer for two reasons:

1. Reduces maintenance upkeep for when we add new guides
1. There's nothing really worth linking to yet

Can very easily be added back in the future if Guides or Writing winds up in our main website's nav structure and we want this to mirror that.

### How to Check Change

The footer used to look like this:

image

It should now look like this:

image

### CODE REVIEW

**Comment by SMakaiTakori** [comment]
@jeffmaher This looks good to me code-wise. I will defer to @admoorgit on design since things don't appear centered anymore and the design may need to be updated.

**Review by SMakaiTakori — APPROVED** [review]

**Comment by admoorgit** [comment]
Kind of a weird thing separate from the footer layout is, if you highlight the text in Safari, it becomes unreadable in some areas. It's fine in Chrome. Likely a browser-specific interpretation. 
image

**Review by admoorgit — CHANGES_REQUESTED** [review]
**Easiest fix, which I am OK with:** left align "About Us" content with the SBA logo 

**Preferred fix, if it's not a heavy lift:** left align "About Us" content with SBA logo, move email and LinkedIn up and add "connect with us" header. If there's room on mobile for 3 columns (work | about | contact), great! if not, ok to knock "connect" under "work" and "about us" and above copyright + SBA
image

**Comment by jeffmaher** [comment]
@admoorgit : Sounds good! I'll code that up!

**Comment by admoorgit** [comment]
Kinda late on responding but this looks good to me!

**Pull request merged**
